import React from 'react';
import { SEO } from '../../allComponents.js';

class MedicalDeviceIntro extends React.Component {
    
    render() {
        return (
            <>
            <SEO title="Medical Industries - Medical Industry Management" />


            <div className="content">

            <h1>Classification of Medical Devices</h1>

            <h2>Criteria for Classification</h2>

            <p>The criteria for classifcation of medical devices are as follows:</p>
            <ol>
            <li>Intended purpose</li>
            <li>How long the device is intended to be in “continuous” use.</li>
            <li>Whether or not the device is invasive (surgically or with respect to body orifices).</li>
            <li>Whether or not the device is implantable.</li>
            <li>Whether or not the device is active.</li>
            <li>Whether or not the device contains a substance, which in its own right is considered to be a medicinal substance and has action ancillary (subservient or subordinate, like a handmaid; auxiliary) to that of the device.</li>
            </ol>

            <p>
            It is usually the intended purpose for use, assigned by the manufacturer to a specific device and not the class assigned to other similar products manufactured by the same of different manufacture that determines the class of medical device. Based on these criteria, medical devices can be categorized into the following: 
            </p>

            <ol>
            <li>Class I medical device: No or low risk
            <ul>
            <li>Class I<sub>m</sub>: Products with a measuring function</li>
            <li>Class I<sub>s</sub>: Sterile products</li>
            </ul>
            </li>
            <li>Class II Medical Device: Moderate risk
            <ul>
            <li>Class II<sub>a</sub></li>
            <li>Class II<sub>b</sub></li>
            </ul>
            </li>
            <li>Class III Medical Device: High risk</li>
            </ol>

            <blockquote>
                
            <ul>
            <li>Only medical devices that are safe and perform as intended should be allowed in the market.</li>
            <li>All classes of medical devices including <strong>I<sub>s</sub>, I<sub>m</sub>, II<sub>a</sub>, II<sub>b</sub></strong> and <strong>III</strong> medical devices require intervention of a third party i.e. the notified body.</li>
            <li>A manufacturer may successfully avoid a particular higher classification by explicitly providing information about the intended purpose of their products in such a way that it falls in a lower class as compared to similar products manufactured by the same or different manufacturers.</li>
            </ul>
            </blockquote>

            <h2>Understanding Key Technical Definitions for Classification Rules:</h2>

            <div className="sep">
            <ul>
            <li><strong>Duration</strong>
            <ol>
            <li><em>Transient.</em> Normally intended for continuous use for less than 60 minutes.</li>
            <li><em>Short term.</em> Normally intended for continuous use for 60 minutes or more but not more than 30 days.</li>
            <li><em>Long term.</em> Normally intended for continuous use for more than 30 days.</li>
            </ol>
            </li>

            <li><strong>Invasive devices</strong>

            <div class="sep">
                
            </div>
            <ol>
            <li><em>Invasive device.</em> A device which, in whole or in part, penetrates inside the body either through a body orifice or through the surface of the body.</li>
            <li><em>Body orifice.</em> Any natural opening in the body as well as the external surface of the eyeball, or any permanent artificial opening such as a stoma.</li>
            <li><em>Surgically invasive device.</em> An invasive device which penetrates inside the body through the surface of the body, with the aid or in the context of surgical operation. (Any device which produces penetration other than through an established body orifice, shall be treated as a surgically invasive device).</li>
            <li><em>Implantable device.</em> Any device which is intended to be totally introduced into the human body or, to replace an epithelial surface or the surface of the eye. Any device intended to be partially introduced into the human body through surgical intervention and intended to remain in place after the procedure for at least 30 days is also considered an implantable device.</li>
            </ol>
            </li>

            <li><strong>Active medical device.</strong> Any medical device, operation of which depends on a source of electrical energy or any source of power other than that directly generated by the human body or gravity and which <mark>acts by converting this energy</mark>. Medical devices intended to transmit energy, substances or other elements between an active medical and the patient, without any significant change, are not considered to be active medical device.</li>

            <li><strong>Therapeutical Device.</strong> Any medical device, whether used alone or in combination with other medical devices, to support, modify, replace or restore biological functions or structures with a view to treatment or alleviation of an illness, injury or handicap.</li>

            <li><strong>Diagnostic Device.</strong> Any medical device, whether used alone or in combination with other medical device, to supply information for detecting, diagnosing , monitoring physiological conditions, states of health, illness or congenital deformities.</li>

            <li><strong>Reusable surgical instrument.</strong> Instruments intended for surgical use by cutting, scratching, scraping, clamping, retracting, clipping or similar procedures, without connection to any active medical device and which can be reused after appropriate procedures have been carried out.</li>

            <li><strong>Central nervous system.</strong> means brain, meninges (dura matter, arachnoid and pia matter) and the spinal cord.</li>

            <li><strong>Central circulatory system.</strong> means the following vessels | pulmonary artery, ascending aorta, coronary artery, common carotid artery, external carotid artery, internal carotid artery, cerebral artery, branchiocephalic trunk, blood vessels of the heart, pulmonary veins, superior vena cava, inferior vena cava.</li>
            </ul>
            </div>






            <h2>Rules per Annex IX</h2>

            <ul>
            <li>Non-invasive devices - 1 through 4</li>
            <li>Invasive devices - 5 through 8</li>
            <li>Active devices or Reusable - 9 through 12</li>
            <li>Special - 13 through 18</li>
            </ul>

            <h3>Non-invasive devices</h3>


            <div class="sep">
            <ul>
            <li><strong>Rule. 1</strong> All non-invasive devices are in Class I, unless one of the rules set out hereinafter applies: Examples, corrective glasses, stethoscope, non-invasive electrodes.</li>
            <li><strong>Rule. 2</strong> All non-invasive devices intended for channelling or storing blood, body liquids or tissues, liquids or gases for the purpose of eventual infusion, administration or introduction into the body are in Class IIa: Examples, Cup and spoon.</li>
            <li><strong>Rule. 3</strong> All non-invasive devices intended for modifying the biological or chemical composition of blood, other body liquids, other liquids intended for infusion into the body are in Class IIb, unless the treatment consists of filtration, centrifugation or exchange of gas, heat, in which case they are in Class IIa.</li>
            <li><strong>Rule. 4</strong> All non-invasive devices which come into contact with injured skin:
            <ul>
            <li>are in Class I if they are intended to be used as a mechanical barrier, for compression or for absorption of exudate (any exuded or secreted substance).</li>
            <li>are in Class IIb if they are intended to be used principally with wound which have breached the dermis and can only heal by secondary intent.</li>
            <li>are in Class IIa in all other cases, including devices principally intended to manage the micro-environment of a wound.</li>
            </ul>
            </li>
            </ul>

            </div>

            <h3>Invasive Devices</h3>

            <div class="sep">
            <ul>
            <li><strong>Rule 5.</strong> All invasive devices with respect to body orifices, other than surgically invasive devices and which are "not" intended for connection to an active medical device:
            <ul>
            <li>are in Class I if they are intended for transient use.</li>
            <li>are in Class IIa if they are intended for short term use, except if they are used in the oral cavity as far as the pharynx, in an ear canal up to the ear drum or in a nasal cavity, in which case they are in Class I.</li>
            <li>are in Class IIb if they are intended for long-term use, except if they are used in the oral cavity as far as the pharynx, in an ear canal up to the ear drum or in a nasal cavity and are not liable to be absorbed by the mucous membrane, in which case they are in Class IIa.</li>
            </ul>
            </li>
            <li><strong>Rule 6.</strong> All surgically invasive devices intended for transient use are in Class IIa unless they are:
            <ul>
            <li>intended specifically to diagnose or monitor or correct a defect of the heart or of the central circulatory system through direct contact with these parts of the body, in which case they are in class III.</li>
            <li>reusable surgical instruments, in which case they are in Class I.</li>
            <li>intended to supply energy in the form of ionizing radiation in which case they are in Class IIb.</li>
            <li>intended to have a biological effect or be wholly or mainly absorbed in which case they are Class IIb.</li>
            <li>intended to administer medicines by means of a delivery system, if this is done in manner that is potentially hazardous taking account of the mode of application in which case they are in Class IIb.</li>
            </ul>
            </li>
            <li><strong>Rule 7.</strong> All surgically invasive devices intended for short-term use are in Class IIa unless they are intended:
            <ul>
            <li>either specifically to diagnose, monitor or correct a defect of the heart or the central circulatory system through direct contact with these parts of the body, in which case they care in Class III.</li>
            <li>or specifically for use in direct contact with the central nervous system, in which case they are in class III.</li>
            <li>or to supply energy in the form of ionizing radiation in which case they are in class IIb.</li>
            <li>or to have a biological effect or to be wholly or mainly absorbed in which case they are in class III.</li>
            <li>or to undergo chemical change in the body, except if the devices are placed in the teeth, or to administer medicines, in which case they are in class IIb.</li>
            </ul>
            </li>
            <li><strong>Rule 8.</strong> All implantable device and long-term surgically invasive devices are in class IIb unless they are intended:
            <ul>
            <li>to be placed in the teeth, in which case they are in class IIa.</li>
            <li>to be used in direct contact with the heart, the central circulatory system or the central nervous system, in which case they are in class III.</li>
            <li>to have a biological effect or to be wholly or mainly absorbed, in which case they are in class III.</li>
            <li>or to undergo chemical change in the body, except if the devices are placed in the teeth, or to administer medicines, in which case they are in class III.</li>
            </ul>
            </li>
            </ul>
            </div>

            <blockquote className="info">
            Note: Keep checking the Annex for updates on these rules.
            </blockquote>
            </div>
            </>
        )
    }
}

export default MedicalDeviceIntro;

